import json                                                                                                                                                                                                                                                                 
from collections import defaultdict                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                             
def clean_crawl_results(input_file, output_file):                                                                                                                                                                                                                           
    # Read the input JSON file                                                                                                                                                                                                                                              
    with open(input_file, 'r') as f:                                                                                                                                                                                                                                        
        data = json.load(f)                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                            
    # Track seen titles and cleaned results                                                                                                                                                                                                                                 
    seen_titles = set()                                                                                                                                                                                                                                                     
    cleaned_data = []                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                            
    for crawl in data:                                                                                                                                                                                                                                                      
        cleaned_results = []                                                                                                                                                                                                                                                
        for result in crawl['results']:                                                                                                                                                                                                                                     
            title = result.get('title', '')                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                            
            # Skip if title is "Title not found" or duplicate                                                                                                                                                                                                               
            if title == "Title not found" or title in seen_titles:                                                                                                                                                                                                          
                continue                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                            
            seen_titles.add(title)                                                                                                                                                                                                                                          
            cleaned_results.append(result)                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                            
        # Only keep crawls that have results                                                                                                                                                                                                                                
        if cleaned_results:                                                                                                                                                                                                                                                 
            cleaned_crawl = {                                                                                                                                                                                                                                               
                'timestamp': crawl['timestamp'],                                                                                                                                                                                                                            
                'pages_crawled': len(cleaned_results),                                                                                                                                                                                                                      
                'results': cleaned_results                                                                                                                                                                                                                                  
            }                                                                                                                                                                                                                                                               
            cleaned_data.append(cleaned_crawl)                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                            
    # Write cleaned data to output file                                                                                                                                                                                                                                     
    with open(output_file, 'w') as f:                                                                                                                                                                                                                                       
        json.dump(cleaned_data, f, indent=4)                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                            
if __name__ == "__main__":                                                                                                                                                                                                                                                  
    input_file = 'crawl_results.json'                                                                                                                                                                                                                                       
    output_file = 'crawled_clean.json'                                                                                                                                                                                                                                      
    clean_crawl_results(input_file, output_file)                                                                                                                                                                                                                            
    print(f"Cleaned data saved to {output_file}") 